version: '3.8'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      TZ: Europe/Moscow
    networks:
      - sharenetwork
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "${MSSQL_USER}", "-P", "${MSSQL_SA_PASSWORD}"]
        interval: 30s
        timeout: 10s
        retries: 5
    volumes:
      - type: volume
        source: db-data-lab6
        target: /var/opt/mssql

volumes:
  db-data-lab6:

networks:
  sharenetwork:
    driver: bridge
